//this file acts as the source of all questions that will be asked in the apply forms and also where we access the questions to display for the application detail page.
const contactInfo = {
    firstname: 'First Name',
    lastname: 'Last Name',
    address: 'Address ',
    age: 'Age',
    city: 'City',
    zip: 'Zip/Postal Code',
    dayphone: 'Phone Number (day)',
    dayphonetype: 'Phone Number Type (day)',
    eveningphone: 'Phone Number (day)',
    eveningphonetype: 'Phone Number Type (day)',
    email: 'Email',
    calltimes: 'Preferred hours of the day for calls'

}

export const adoptQuestions = {
    ...contactInfo,
    question1: 'What is the noise level of your place?',
    question2: 'Housing type',
    question3: 'Housing ownership',
    question4: 'Are there allergies in your household?',
    question5: 'Do you have any intentions of breeding?',
    question6: 'Do you intend to declaw?',
    question7: 'Do you plan on moving within the next year? If so, what will you do with your cat?',
    question8: 'Where will this cat be kept during the day and night?',
    question9: 'How many hours a day will the cat be without human companionship? ',
    question10: 'Who will take care of the cat if you are out of town?',
    question11: 'Do you have children? If so, what are their ages?',
    question12: 'Are your children experienced with cats?',
    question13: 'Will the cat be allowed to go outside?',
    question14: 'List any animals currently in your care',
    question15: 'If you have ever surrendered an animal to a shelter, please explain the circumstances ',
    question16: 'If you have ever had an animal euthanized, please explain the situation ',
    question17: 'Why do you want an animal companion?',
    question18: 'Do you understand that this cat will need animal vet visits beginning immediately? ',
    question19: 'Who will be responsible for the care and cost of this cat? ',
    question20Name: 'Family Vet Name',
    question20Phone: 'Family Vet Phone Number',
    question21Ref: 'Reference 1 Name',
    question21Phone: 'Reference 1 Number',
    question21Ref2: 'Reference 2 Name',
    question21Phone2: 'Reference 2 Number',
};
export const fosterQuestions = {
    ...contactInfo,
    question1: 'Do you have a device to take pictures with?',
    question2: 'How will you transport your foster cats?',
    question3: 'Why would you like to foster with NVARS?',
    question4: 'Have you fostered before? If so, with who?',
    question5: 'Housing type',
    question6: 'Housing ownership',
    question7: 'How active/noisy is your household?',
    question8: 'Who will be the primary caregiver for your fosters?',
    question9: `Primary caregiver's age?`,
    question10: 'Primary caregiver previous experience?',
    question11: 'How often will the cat be alone during the week?',
    question12: 'How about during the weekend?',
    question13: 'Do you have a seperate room for fosters?',
    question14: 'Please list all children in your household (names and ages) ',
    question15: 'Do you currently have any cats?',
    question16: 'Do you have any other pets currently?',
};
export const volunteerQuestions = {
    ...contactInfo,
    question1: 'Are you applying for a specific position?',
    question2: 'Do you have any relevant experience?',
    question3: 'Occupation',
    question4: 'Employer',
    question5: 'How often do you plan to volunteer?',
    question6: 'When are you able to begin volunteering?',
    question7: 'May we contact you at work? (seldom done)',
    question8: `Do you have a driver's license and vehicle?`,
    question9: `Please tell us briefly why you wish to become a volunteer with Nicola Valley Animal Rescue `,
    question10: `Please list all pets currently in your care. Include their name, species, age, sex and spay/neuter status `,
    question11: 'What type of animal experience do you have?',
    question12: 'Briefly describe any organizations you have volunteered with. Include your responsibilities and duration ',
    question13: 'What are you hobbies and skills?',
    question14: 'Is there anything else you would like to share about yourself? ',
};

